from enum import StrEnum


class UserRole(StrEnum):
    CUSTOMER = "CUSTOMER"
    APPROVER = "APPROVER"
    ADMIN = "ADMIN"


class TicketIntent(StrEnum):
    REFUND = "REFUND"
    EXCHANGE = "EXCHANGE"
    EXCEPTION = "EXCEPTION"
    CONSULTATION = "CONSULTATION"


class TicketStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    WAITING_USER = "WAITING_USER"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class RefundStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PROCESSING = "PROCESSING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    TRANSFERRED = "TRANSFERRED"
    ESCALATED = "ESCALATED"


class ApprovalDecision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    MODIFY_APPROVE = "MODIFY_APPROVE"
    TRANSFER = "TRANSFER"


class ManualReviewStatus(StrEnum):
    PENDING = "PENDING"
    RESOLVED = "RESOLVED"
    UNRESOLVABLE = "UNRESOLVABLE"


class ManualReviewCategory(StrEnum):
    MODEL_FAILURE = "MODEL_FAILURE"
    PAYMENT_UNKNOWN = "PAYMENT_UNKNOWN"
    DATA_INCONSISTENCY = "DATA_INCONSISTENCY"
    SECURITY_REJECTION = "SECURITY_REJECTION"
